### ISSUE TITLE
Add 'Friends and Family Test' data

### ISSUE THREAD

**Issue by stevenday** [mysociety/citizenconnect#1213]
This is a master ticket - see the tasks below for individual tickets.

Survey data which is stored against both Organisation Parents and Organisations.

Comes from CSV files manually uploaded by the NHS.

The relevant bits of info from the spec follow, which I'll then break up into specific tickets.
### Adding new data
- User enters admin panel
- User is presented list of data already uploaded, ordered  by month, type and context
- Users clicks ‘upload FFT data’
- User selects type to upload:
  - A&E
  - Inpatient
- User selects context to upload:
  - Trust
  - Site
- User selects month to be uploaded
- User adds CSV sheet
### Removing specific data
- User enters ‘FFT’ admin panel
- User is presented list of data already uploaded, ordered  by month, type and context
- User clicks ‘remove’ aside row containing data to be removed
- User confirms deletion

**Note:** If we make the other parts correctly, the Django admin should be sufficient for this on its' own.
### Displaying data on organisations/organisation parents

Add a ‘Friends and Family’ tab to public or private pages (as appropriate) containing:
- Introduction to the rating, consistent across all providers’ tabs
- A bar chart showing the most recent month’s uploaded A&E and inpatient data with breakdown for each response:
  - Extremely likely
  - Likely
  - Neither
  - Unlikely
  - Extremely unlikely
  - Don’t know
- The overall test score for A&E and inpatient data
- A line graph showing the most recent 6 month’s overall score for A&E and inpatient data
### Data

Per site CSV looks like:

``` csv
Area Team Code,Code,Name,Site Code,Site Name,Total Responses,Total Eligible,Response Rate,Friends and Family Test Score,,Extremely Likely,Likely,Neither,Unlikely,Extremely Unlikely,Don't Know
Q44,RJR,COUNTESS OF CHESTER HOSPITAL NHS FOUNDATION TRUST,RJR05,Countess Of Chester Hospital - RJR05,498,"1,303",38.20%,79,,346,79,6,0,0,67
```

Per Trust CSV looks like:

``` csv
Area Team Code,Code,Name,Total Responses,Total Eligible,Response Rate,Friends and Family Test Score,,Extremely Likely,Likely,Neither,Unlikely,Extremely Unlikely,Don't Know,,SMS/Text / Smartphone App,Electronic tablet/kiosk at point of discharge,Paper / postcard at point of discharge,"Paper survey, sent to the patients home",Telephone survey once patient is home,Online survey once patient is home,Other
Q44,RJR,COUNTESS OF CHESTER HOSPITAL NHS FOUNDATION TRUST,498,"1,303",38.20%,79,,346,79,6,0,0,67,,0,0,497,0,0,0,1
```
## Tasks
- [x] Add a new model for storing friends and family data - #1214
- [ ] Add a new view for displaying the data on orgs #1216
- [ ] Add a new view for displaying the data on trusts #1216
- [x] Add an admin page for uploading data #1217
