### ISSUE TITLE
Add the concept of NHS Trusts

### ISSUE THREAD

**Issue by stevenday** [mysociety/citizenconnect#738]
This is going to be one huge meta issue, which I will split out as appropriate. However, it helps to break it down into chunks here first.

This requires:
## Database model
- [x] Extracted to #744
- [x] Remove email and secondary_email fields from organisations (see #751)
## User accounts
- [x] Extracted to #745
## Authorisation
- [x] Extracted to #746
## Supplied data and imports
- [x] Extracted to #747
## Interval Counts
- [x] Extracted to #748 
## Escalation emails
- [x] Extracted to #749
## Problem emails
- [x] Extracted to #750 
## Views
- [x] Adding Trust dashboards and updating tabs - extracted to #757
- [x] Split up OrganisationSummary - extracted to #767 
- [x] Splitting OrganisationProblems - extracted to #768
- [x] Splitting OrganisationReviews into a new TrustReviews for private views and refactoring OrganisationReviews to be for the public only. Extracted to #762 
- [x] Renaming and refactoring OrganisationBreaches to be TrustBreaches - extracted to #760
- [x] Adding an "organisation" filter to the filter form - extracted to #759 
- [x] Update escalation views - extracted to #754
## Tests
- [x] Oh the tests, they will be mightily unhappy with all this.
- [x] In particular, AuthorisationTestCase is going to need some serious refactoring, and any tests which inherit from it (read: _loads_) will need checking to make sure that they're logged in as the right trust user rather than the right org user when checking permissions or doing things.
