### ISSUE TITLE
Change moderated and publication_status flags to be one flag with three options

### ISSUE THREAD

**Issue by stevenday** [mysociety/citizenconnect#786]
Options being:
`NOT_MODERATED`
`HIDDEN`
`PUBLISHED`
The latter two both being equal to: `MODERATED`

This requires:
- [x] Changing the fields on the model
- [x] A data migration to move existing problems into the right new status
- [x] Changing the api (I think we can always assume that anything they send us is automatically `PUBLISHED`)
- [x] Updating the api docs
- [x] Changing the moderation form's clean methods (because it automatically sets `MODERATED`)
- [x] Changing the querysets for problems which check moderated or unmoderated
- [x] Changing test code which sets `moderated` to test things (problem access tests done in #784)
- [x] Changing problem access code which checks moderated (Done in #784)
- [x] Changing problem templates which check moderated (Done in #784)
- [x] Updating the code which turns changes in models into a history
- [x] Fixing any other broken tests
- [x] Updating the example problems
