### ISSUE TITLE
Add support for image uploads in problems

### ISSUE THREAD

**Issue by BenJam** [mysociety/citizenconnect#793]
This is a placeholder ticket for >1 more tickets addressing issues below:
- [x] Store images in the database. (#861)
- [x] Serve the images from the server (#866)
- [x] The problem form to be adapted to allow a user to upload a picture. The following file types will be allowed: jpeg, bmp, gif. Multiple picture upload will be allowed up to a maximum of 3 pictures. Suggested position of the upload picture box is underneath the text section – but this will be confirmed with one design iteration. (#862)
- [x] Pictures will be sent with the rest of the problem details directly to a parent (trust). (#863)
- [x] All pictures will be treated as ‘problem text’ and will go through moderation process with case handler/second tier moderator (#864)
- [x] Display images on the site (#865)
- [x] API will be modified similarly to accept images. (#867)
- [x] Create backups (#868)
